// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "consignment-notes",
            "region": "eu-central-1"
        }
    ],
    "aws_user_files_s3_bucket": "consoleapp878f602f853546e3ba49e8455ce9d894",
    "aws_user_files_s3_bucket_region": "eu-central-1",
    "aws_content_delivery_bucket": "ecmr-console-app",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://ecmr-console-app.s3-website.eu-central-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-central-1:75903d70-171b-4873-8384-e1f4c59820e1",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Ai4du5la5",
    "aws_user_pools_web_client_id": "18bdqfpdm5i9siskv1sfl75j77",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://s5qjr3vjcfd5ndcd3sqkdvrnf4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
